Recharge_Mobile/Areas/AdminArea/Controllers/RegularRechargeController.cs
using CDStore.Models.Filters;
using Recharge_Mobile.Areas.RechargeArea.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recharge_Mobile.Areas.AdminArea.Controllers
{
    [CAuthFilter(RoleName = "Admin")]
    public class RegularRechargeController : Controller
    {
        RegularRechargeDAO regularRechargeDAO;
        // GET: RechargeArea/RegularRecharge
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateRegularRecharge()
        {
            RegularRechargeVM vm = new RegularRechargeVM();
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRegularRecharge(RegularRechargeVM vm)
        {
            if (ModelState.IsValid)
            {
                regularRechargeDAO = new RegularRechargeDAO();
                regularRechargeDAO.CreateItem(vm);
                return RedirectToAction("CreateRegularRecharge");
            }
            return View(vm);
        }

        public ActionResult ViewRRList()
        {
            regularRechargeDAO = new RegularRechargeDAO();
            var resultList = regularRechargeDAO.GetList();
            return View(resultList);
        }

        public ActionResult EditRR(int id)
        {
            regularRechargeDAO = new RegularRechargeDAO();
            var result = regularRechargeDAO.GetItemById(id);
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRR(RegularRechargeVM vm)
        {
            regularRechargeDAO = new RegularRechargeDAO();
            if (ModelState.IsValid)
            {
                regularRechargeDAO.EditItem(vm);
                return RedirectToAction("ViewRRList");
            }
            return View(vm);
        }

        public ActionResult ActivateRR(int id)
        {
            regularRechargeDAO = new RegularRechargeDAO();
            regularRechargeDAO.ActivateItem(id);
            return RedirectToAction("ViewRRList");
        }

        public ActionResult DeactivateRR(int id)
        {
            regularRechargeDAO = new RegularRechargeDAO();
            regularRechargeDAO.DeactivateItem(id);
            return RedirectToAction("ViewRRList");
        }
    }
}

Recharge_Mobile/Areas/RechargeArea/Controllers/RegularRechargeController.cs
using Recharge_Mobile.Areas.RechargeArea.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recharge_Mobile.Areas.RechargeArea.Controllers
{
    public class RegularRechargeController : Controller
    {
        RegularRechargeDAO regularRechargeDAO;
        // GET: RechargeArea/RegularRecharge
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateRegularRecharge()
        {
            RegularRechargeVM vm = new RegularRechargeVM();
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRegularRecharge(RegularRechargeVM vm)
        {
            if (ModelState.IsValid)
            {
                regularRechargeDAO = new RegularRechargeDAO();
                regularRechargeDAO.CreateItem(vm);
                return RedirectToAction("CreateRegularRecharge");
            }
            return View(vm);
        }

        public ActionResult ViewRRList()
        {
            regularRechargeDAO = new RegularRechargeDAO();
            var resultList = regularRechargeDAO.GetList();
            return View(resultList);
        }

        public ActionResult EditRR(int id)
        {
            regularRechargeDAO = new RegularRechargeDAO();
            var result = regularRechargeDAO.GetItemById(id);
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRR(RegularRechargeVM vm)
        {
            regularRechargeDAO = new RegularRechargeDAO();
            if (ModelState.IsValid)
            {
                regularRechargeDAO.EditItem(vm);
                return RedirectToAction("ViewRRList");
            }
            return View(vm);
        }

        public ActionResult ActivateRR(int id)
        {
            regularRechargeDAO = new RegularRechargeDAO();
            regularRechargeDAO.ActivateItem(id);
            return RedirectToAction("ViewRRList");
        }

        public ActionResult DeactivateRR(int id)
        {
            regularRechargeDAO = new RegularRechargeDAO();
            regularRechargeDAO.DeactivateItem(id);
            return RedirectToAction("ViewRRList");
        }
    }
}

Recharge_Mobile/Areas/AdminArea/Views/RegularRecharge/CreateRegularRecharge.cshtml
@model Recharge_Mobile.Areas.RechargeArea.Models.RegularRechargeVM

@{
    ViewBag.Title = "CreateRegularRecharge";
    Layout = "~/Areas/AdminArea/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create Regular Recharge</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr /><br/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Recharge Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.RRName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RRName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Base Time (Minute)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BasteTimeMinute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BasteTimeMinute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Bonus Time (Minute)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BonusTimeMinute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BonusTimeMinute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Price</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Duration (Day)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DurationDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DurationDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Description</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-gradient ml-3 d-none d-xl-inline-block" onclick="return confirm('Are you sure to create new?')" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Recharge_Mobile/Areas/AdminArea/Views/RegularRecharge/EditRR.cshtml
@model Recharge_Mobile.Areas.RechargeArea.Models.RegularRechargeVM

@{
    ViewBag.Title = "EditRR";
    Layout = "~/Areas/AdminArea/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit Regular Recharge</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr /><br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="display:none;">
            @Html.LabelFor(model => model.RRechargeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RRechargeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RRechargeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Recharge Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.RRName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RRName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Base Time (Minute)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BasteTimeMinute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BasteTimeMinute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Bonus Time (Minute)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BonusTimeMinute, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BonusTimeMinute, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Price</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Duration (Day)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DurationDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DurationDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Description</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-gradient ml-3 d-none d-xl-inline-block" onclick="return confirm('Are you sure to save changes?')" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewRRList","RegularRecharge")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Recharge_Mobile/Areas/AdminArea/Views/RegularRecharge/ViewRRList.cshtml
@model IEnumerable<Recharge_Mobile.Areas.RechargeArea.Models.RegularRechargeVM>

@{
    ViewBag.Title = "ViewRRList";
    Layout = "~/Areas/AdminArea/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="color: purple; text-align: center">Regular Recharge List</h2><hr /><br />

<p>
    @Html.ActionLink("Create New", "CreateRegularRecharge", "RegularRecharge", new { @class = "btn btn-style-4 btn-dark" })
</p>
<table class="table table-hover">
    <tr>
        <th>
            Package Name
        </th>
        <th>
            Base Time (minutes)
        </th>
        <th>
            Bonus Time (minutes)
        </th>
        <th>
            Total Time (minutes)
        </th>
        <th>
            Price
        </th>
        <th>
            Duration (days)
        </th>
        <th>
            Description
        </th>
        <th>
            Status
        </th>
        <th>
            Actions
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RRName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BasteTimeMinute)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BonusTimeMinute)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalTimeMinute)
        </td>
        <td>
            $@Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DurationDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditRR", new { id = item.RRechargeId }) |
            @if (item.Status == "Active")
            {
                @Html.ActionLink("Deactivate", "DeactivateRR", new { id = item.RRechargeId })
            }
            else
            {
                @Html.ActionLink("Activate", "ActivateRR", new { id = item.RRechargeId })
            }
        </td>
    </tr>
}

</table>