Recharge_Mobile/Areas/AdminArea/Controllers/AdminCustomerController.cs
using CDStore.Models.Filters;
using Recharge_Mobile.Areas.AdminArea.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recharge_Mobile.Areas.AdminArea.Controllers
{
    [CAuthFilter(RoleName = "Admin")]
    public class AdminCustomerController : Controller
    {
        AdminCustomerDAO adminCustomerDAO;
        // GET: AdminArea/AdminCustomer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CustomerList()
        {
            adminCustomerDAO = new AdminCustomerDAO();
            var resultList = adminCustomerDAO.GetCustomerList();
            return View(resultList);
        }
        public ActionResult CustomerListByPhone(string searchNumber)
        {
            adminCustomerDAO = new AdminCustomerDAO();
            var resultList = adminCustomerDAO.GetCustomerListByPhone(searchNumber);
            return View("CustomerList", resultList);
        }

        public ActionResult CustomerDetails(int id)
        {
            adminCustomerDAO = new AdminCustomerDAO();
            var results = adminCustomerDAO.GetCustomerDetails(id);
            ViewBag.CustomerTransactions = results.Item2;
            return View(results.Item1);
        }

        public ActionResult ActivateCustomer(int id)
        {
            adminCustomerDAO = new AdminCustomerDAO();
            adminCustomerDAO.ActivateCustomer(id);
            return RedirectToAction("CustomerList");
        }

        public ActionResult DeactivateCustomer(int id)
        {
            adminCustomerDAO = new AdminCustomerDAO();
            adminCustomerDAO.DeactivateCustomer(id);
            return RedirectToAction("CustomerList");
        }
    }
}

Recharge_Mobile/Areas/AdminArea/Views/AdminCustomer/CustomerDetails.cshtml
@model Recharge_Mobile.Areas.AdminArea.Models.AdminCustomerDetailsVM
@using Recharge_Mobile.Areas.AdminArea.Models

@{
    ViewBag.Title = "CustomerDetails";
    Layout = "~/Areas/AdminArea/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="jumbotron">
    <h3>Information</h3>
    <hr class="mt-2 mb-3">
    <div class="row">
        <label class="col-lg-6" for="account-fn">First Name: @Model.FirstName </label><br />
        <label class="col-lg-6" for="account-fn">Last Name: @Model.LastName </label><br />
        <label class="col-lg-6" for="account-fn">Email: @Model.Email </label><br />
        <label class="col-lg-6" for="account-fn">Address: @Model.Address </label><br />
        <label class="col-lg-6" for="account-fn">Lock: @Model.Lock </label><br />
        <label class="col-lg-6" for="account-fn">Busy: @Model.Busy </label><br />
        <label class="col-lg-6" for="account-fn">Status: @Model.Status </label>
    </div>
</div>
<div class="jumbotron">
    <h3>Main Balance</h3>
    <hr class="mt-2 mb-3">
    <div class="row">
        @*<label class="col-lg-6" for="account-fn">Customer ID: @Model.CustomerId </label><br />*@
        <label class="col-lg-6" for="account-fn">Phone Number: @Model.PhoneNumber </label><br />
        <label class="col-lg-6" for="account-fn">Time Remain (Minute): @Model.TimeRemain </label><br />
        <label class="col-lg-6" for="account-fn">Regular Time: @Model.RegularTime </label><br />
        <label class="col-lg-6" for="account-fn">Special Time: @Model.SpecialTime </label><br />
        <label class="col-lg-6" for="account-fn">Debit Amount: $@Model.DebitAmount </label>
        @if (Model.DebitAmount > 0)
        {
            <label class="col-lg-6" for="account-fn">Time To Pay: @Model.TimeToPay </label>
        }
    </div>
</div>



@if (ViewBag.CustomerTransactions != null && ((List<TransactionAdminVM>)(ViewBag.CustomerTransactions)).Count() >= 1)
{
<table class="table table-striped">
    <tr>
        @*<th>
            Transaction ID
        </th>*@
        @*<th>
            PhoneNumber
        </th>*@
        <th>
            Type Recharge
        </th>
        @*<th>
            RRechargeId
        </th>
        <th>
            SRechargeId
        </th>*@
        <th>
            Type Packet
        </th>
        <th>
            Recharge Name
        </th>
        <th>
            Price
        </th>
        <th>
            Date
        </th>
        <th>
            Post Payment
        </th>
        <th>
            Status
        </th>
    </tr>

    @foreach (TransactionAdminVM item in (List<TransactionAdminVM>)(ViewBag.CustomerTransactions))
    {
        <tr>
            @*<td>
                @item.TransactionId
            </td>*@
            @*<td>
                @item.PhoneNumber
            </td>*@
            <td>
                @item.PaymentMethod
            </td>
            @*<td>
                @item.RRechargeId
            </td>
            <td>
                @item.SRechargeId
            </td>*@
            <td>
                @item.RechargeType
            </td>
            <td>
                @item.RechargeName
            </td>
            <td>
                @item.Amount
            </td>
            <td>
                @item.DateTime
            </td>
            <td>
                @item.PostPayment
            </td>
            <td>
                @item.Status
            </td>
        </tr>
    }
</table>

}

@Html.ActionLink("Back to customer list", "CustomerList", new {Area = "AdminArea"})

Recharge_Mobile/Areas/AdminArea/Views/AdminCustomer/CustomerList.cshtml
@model IEnumerable<Recharge_Mobile.Areas.AdminArea.Models.AdminCustomerListVM>

@{
    ViewBag.Title = "CustomerList";
    Layout = "~/Areas/AdminArea/Views/Shared/_LayoutAdmin.cshtml";
}

<h3 style="color: purple; text-align: center">Customer List</h3>
<div class="container">
    <div class="row mb-3">
        <div class="col"></div>
        <div class="col">
            <div class="float-right">
                @using (Html.BeginForm("CustomerListByPhone", "AdminCustomer", new { area = "AdminArea" }))
                {
                    <input class="" type="text" id="searchNumber" name="searchNumber" placeholder="Search by phone" onchange="this.form.submit()">
                }
            </div>
        </div>
    </div>
</div>
<table class="table table-hover">
    <tr>
        <th style="display:none">id</th>
        <th>
            Phone Number
        </th>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Busy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="display:none">
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Busy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.ActionLink("Details", "CustomerDetails", new { id = item.CustomerId }) |
                @if (item.Status == "Active")
                {
                    @Html.ActionLink("Deactivate", "DeactivateCustomer", new { id = item.CustomerId })
                }
                else
                {
                    @Html.ActionLink("Activate", "ActivateCustomer", new { id = item.CustomerId })
                }
            </td>
        </tr>
    }

</table>