Recharge_Mobile/Areas/Recharge/Models/PaypalConfiguration.cs
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Recharge_Mobile.Areas.Recharge.Models
{
    public class PaypalConfiguration
    {
        public readonly static string ClientID;
        public readonly static string ClientSecret;

        static PaypalConfiguration()
        {
            var config = GetConfig();
            ClientID = config["clientId"];
            ClientSecret = config["clientSecret"];
        }

        public static Dictionary<string, string> GetConfig()
        {
            return ConfigManager.Instance.GetProperties();
        }
        //Create access token
        private static string GetAccessToken()
        {
            return new OAuthTokenCredential(ClientID, ClientSecret, GetConfig()).GetAccessToken();
        }

        public static APIContext GetAPIContext()
        {
            var apiContext = new APIContext(GetAccessToken());
            apiContext.Config = GetConfig();
            return apiContext;
        }

    }
}

Recharge_Mobile/Areas/Recharge/Models/PaypalLogger.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace Recharge_Mobile.Areas.Recharge.Models
{
    public class PaypalLogger
    {
        public static string LogDirectoryPath = Environment.CurrentDirectory;
        public static void Log(string msg)
        {
            try
            {
                StreamWriter str = new StreamWriter(LogDirectoryPath + "\\PaypalError.log", true);
                str.WriteLine("{0}--->{1}", DateTime.Now.ToString("MM/dd/yyyy HH:mm:ss"), msg);
            }
            catch (Exception)
            {
                throw;
            }
        }

    }
}

Recharge_Mobile/Areas/Recharge/Models/Views/RRechargeModelView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Recharge_Mobile.Areas.Recharge.Models
{
    public class RRechargeModelView
    {
        public int RRechargeId { get; set; }
        public string RRName { get; set; }
        public long BaseTime { get; set; }
        public long BonusTime { get; set; }
        public long TotalTime { get; set; }
        public decimal Price { get; set; }
        public long Duration { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }

        public RRechargeModelView()
        {

        }

        public RRechargeModelView(int rRechargeId, string rRName, long baseTime, long bonusTime, long totalTime, decimal price, long duration, string description, string status)
        {
            RRechargeId = rRechargeId;
            RRName = rRName;
            BaseTime = baseTime;
            BonusTime = bonusTime;
            TotalTime = totalTime;
            Price = price;
            Duration = duration;
            Description = description;
            Status = status;
        }
    }
}

Recharge_Mobile/Areas/Recharge/Models/Views/SRechargeModelView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Recharge_Mobile.Areas.Recharge.Models
{
    public class SRechargeModelView
    {
        public int SRechargeId { get; set; }
        public string SRName { get; set; }
        public long Duration { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }

        public SRechargeModelView()
        {

        }

        public SRechargeModelView(int sRechargeId, string sRName, long duration, decimal price, string description, string status)
        {
            SRechargeId = sRechargeId;
            SRName = sRName;
            Duration = duration;
            Price = price;
            Description = description;
            Status = status;
        }
    }
}

Recharge_Mobile/Areas/Recharge/Models/Views/TransactionModelView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Recharge_Mobile.Areas.Recharge.Models.Views
{
    public class TransactionModelView
    {
    }
}

Recharge_Mobile/Areas/Recharge/Controllers/PayPalController.cs
using PayPal.Api;
using Recharge_Mobile.Areas.Recharge.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recharge_Mobile.Areas.Recharge.Controllers
{
    public class PayPalController : Controller
    {
        //work with paypal payment
        private Payment payment;

        //create a payment using an APIContext
        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {
            var lsItem = new ItemList() { items = new List<Item>() };
            lsItem.items.Add(new Item { name = TempData["PackageName"].ToString(), currency = "USD", price = TempData["Price"].ToString(), quantity = "1", sku = "sku" });

            var payer = new Payer()
            {
                payment_method = "paypal",
                payer_info = new PayerInfo
                {
                    email = "" //personal account
                }

            };
            var redictUrl = new RedirectUrls()
            {
                cancel_url = redirectUrl,
                return_url = redirectUrl
            };
            var detail = new Details() { tax = "0", shipping = "0", subtotal = TempData["Price"].ToString() }; //subtotal: sum(price*quantity) if sum is incorrect, it will return an error 400.
            var amount = new Amount() { currency = "USD", details = detail, total = TempData["Price"].ToString() }; //total= tax + shipping + subtotal
            var transList = new List<Transaction>();
            transList.Add(new Transaction
            {
                description = "Test Payment",
                invoice_number = Convert.ToString((new Random()).Next(100000)),
                amount = amount,
                item_list = lsItem,

            });
            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transList,
                redirect_urls = redictUrl
            };
            return this.payment.Create(apiContext);
        }
        //create execute payment method
        private Payment ExecutePayment(APIContext apiContext, string payerID, string paymentID)
        {
            var paymentExecute = new PaymentExecution() { payer_id = payerID };
            this.payment = new Payment() { id = paymentID };
            TempData["paymentID"] = paymentID;
            return this.payment.Execute(apiContext, paymentExecute);
        }
        //create method
        public ActionResult PaymentWithPaypal()
        {
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                string payerID = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerID))
                {
                    //create a payment
                    string baseUri = Request.Url.Scheme + "://" + Request.Url.Authority + "/Paypal/PaymentWithPaypal?guid=";
                    string guid = Convert.ToString((new Random()).Next(100000));
                    var createdPayment = CreatePayment(apiContext, baseUri + guid);

                    var link = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = string.Empty;
                    while (link.MoveNext())
                    {
                        Links links = link.Current;
                        if (links.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            paypalRedirectUrl = links.href;
                        }
                    }
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    var guid = Request.Params["guid"];
                    var executePayment = ExecutePayment(apiContext, payerID, Session[guid] as string);
                    if (executePayment.state.ToLower() != "approved")
                    {
                        return View("Failure");
                    }
                }
            }
            catch (PayPal.PaymentsException ex)
            {
                PaypalLogger.Log("Error: " + ex.Message);
                return View("Failure");
            }
            return RedirectToAction("CheckoutPaypal", "Recharge", new { Area = "Recharge" });
            //return RedirectToAction("Success", "PayPal", new { Area = "Recharge" });
        }
        
    }
}

Recharge_Mobile/Areas/User/Controllers/UserController.cs
using Recharge_Mobile.Areas.User.Models.DAO;
using Recharge_Mobile.Areas.User.Models.Views;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recharge_Mobile.Areas.User.Controllers
{
    public class UserController : Controller
    {
        public ActionResult AccountDetail()
        {
            var account = Session["accountInfo"] as CustomerRechargeModelView;
            UserDAO userDAO = new UserDAO();
            var accountDetail = userDAO.AccountDetail(account.PhoneNumber);
            return View(accountDetail);
        }

        // GET: User/Login/Details/5
        public ActionResult AccountSetting()
        {
            var account = Session["accountInfo"] as CustomerRechargeModelView;
            UserDAO userDAO = new UserDAO();
            var accountInfor = userDAO.AccountSetting(account.PhoneNumber);
            return View(accountInfor);
        }
        [HttpPost]
        public ActionResult AccountSetting(string firstname, string lastname, string email, string address)
        {
            var account = Session["accountInfo"] as CustomerRechargeModelView;
            AccountModelView accountModelView = new AccountModelView()
            {
                PhoneNumber = account.PhoneNumber,
                FirstName = firstname,
                LastName = lastname,
                Email = email,
                Address = address
            };
            UserDAO userDAO = new UserDAO();
            userDAO.AccountChange(accountModelView);
            return View();
        }


        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(string oldpassword, string newpassword, string repassword)
        {
            //Check password
            var account = Session["accountInfo"] as CustomerRechargeModelView;
            UserDAO userDAO = new UserDAO();
            var AccountPass = userDAO.AccountPassword(account.PhoneNumber);
            if(oldpassword != AccountPass)
            {
                TempData["oldpassword"] = "Wrong Password!";
                return View();
            } else
            {
                //Check confirm password
                if (newpassword != repassword)
                {
                    TempData["repassword"] = "Confirm password have to same as above!";
                    return View();
                } else
                {
                    TempData["success"] = "Your password had been change!";
                    userDAO.PasswordChange(account.PhoneNumber, newpassword);
                    return View();
                }
            }
        }

        public ActionResult TransactionList()
        {
            var account = Session["accountInfo"] as CustomerRechargeModelView;
            UserDAO userDAO = new UserDAO();
            var TransList = userDAO.TransactionList(account.PhoneNumber);
            return View(TransList);
        }


        public ActionResult AccountDebit()
        {
            var account = Session["accountInfo"] as CustomerRechargeModelView;
            UserDAO userDAO = new UserDAO();
            var debitTransactions = userDAO.DebitTransactionList(account.PhoneNumber);
            return View(debitTransactions);
        }

    }
}

Recharge_Mobile/Areas/Recharge/Views/Recharge/CheckoutComplete.cshtml
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Title-->
<div class="page-title d-flex" aria-label="Page title" style="background-image: url(img/page-title/shop-pattern.jpg);">
    <div class="container text-left align-self-center">
        <h1 class="page-title-heading">Checkout</h1>
    </div>
</div>
<!-- Page Content-->
<div class="container pb-5 mb-3">
    <!-- Checkout: Complete-->
    <div class="wizard pb-3">
        <div class="wizard-body pt-2 text-center">
            <h3 class="h4 pb-3">Thank you for your order!</h3>
            @*<p class="mb-2">Your order has been placed and will be processed as soon as possible.</p>*@
            <p class="mb-2">Make sure you make note of your order number, which is <strong>34VB5540K83.</strong></p>
            <p>You will be receiving an email shortly with confirmation of your order.</p>
            <a class="btn btn-secondary mt-3 mr-3" href="@Url.Action("RechargeDetail","Recharge", new { Area = "Recharge" })">Go Back  Shopping</a>
        </div>
    </div>
</div>

Recharge_Mobile/Areas/Recharge/Views/Recharge/CheckoutPayment.cshtml
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Title-->
<div class="page-title d-flex" aria-label="Page title" style="background-image: url(img/page-title/shop-pattern.jpg);">
    <div class="container text-left align-self-center">
        <h1 class="page-title-heading">Checkout</h1>
    </div>
</div>
<!-- Page Content-->
<div class="container pb-4 mb-2">
    <div class="row">
        <!-- Checkout: Payment-->
        <div class="col-xl-9 col-lg-8 pb-5">
            <div class="wizard">
                @*<div class="wizard-steps d-flex flex-wrap flex-sm-nowrap justify-content-between">
                    <a class="wizard-step" href="checkout-address.html"><i class="fe-icon-check-circle"></i>1. Address</a><a class="wizard-step" href="checkout-shipping.html"><i class="fe-icon-check-circle"></i>2. Shipping</a>
                    <div class="wizard-step active">3. Payment</div><a class="wizard-step" href="checkout-review.html">4. Review</a>
                </div>*@
                <div class="wizard-body">
                    <h3 class="h5 pb-3">Choose Payment Method</h3>
                    <div class="accordion accordion-style-2" id="accordion" role="tablist">
                        <div class="card">
                            <div class="card-header" role="tab">
                                <h6><a class="pl-0" href="#card" data-toggle="collapse"><i class="fe-icon-credit-card"></i>Pay with Credit Card</a></h6>
                            </div>
                            <div class="collapse show" id="card" data-parent="#accordion" role="tabpanel">
                                <div class="card-body px-0">
                                    <p>We accept following credit cards:&nbsp;&nbsp;<img class="d-inline-block align-middle" src="~/Content/img/credit-cards.png" style="width: 120px;" alt="Cerdit Cards"></p>
                                    <div class="card-wrapper"></div>
                                    @using (Html.BeginForm("CheckoutPayment", "Recharge", FormMethod.Post, new { paymentMethod = "Visa", @class = "interactive-credit-card row" }))
                                    {
                                        <div class="form-group col-sm-6">
                                            <input class="form-control" type="text" name="number" placeholder="Card Number" required>
                                        </div>
                                        <div class="form-group col-sm-6">
                                            <input class="form-control" type="text" name="name" placeholder="Full Name" required>
                                        </div>
                                        <div class="form-group col-sm-3">
                                            <input class="form-control" type="text" name="expire" placeholder="MM/YY" required>
                                        </div>
                                        <div class="form-group col-sm-3">
                                            <input class="form-control" type="text" name="cvc" placeholder="CVC" required>
                                        </div>
                                        <div class="col-sm-6">
                                            <button class="btn btn-primary btn-block mt-0" type="submit">Submit</button>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab">
                                <h6><a class="collapsed pl-0" href="#paypal" data-toggle="collapse"><i class="socicon-paypal"></i>Pay with PayPal</a></h6>
                            </div>
                            <div class="collapse" id="paypal" data-parent="#accordion" role="tabpanel">
                                <div class="card-body px-0">
                                    <p><strong>PayPal</strong> - the safer, easier way to pay</p>
                                    <a href="@Url.Action("PaymentWithPaypal", "PayPal", new { Area = "Recharge" })" class="btn btn-primary my-2 form-control">Login</a>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab">
                                <h6><a class="collapsed pl-0" href="#debit" data-toggle="collapse"><i class="fe-icon-shopping-bag"></i>Pay with Debit</a></h6>
                            </div>
                            <div class="collapse" id="debit" data-parent="#accordion" role="tabpanel">
                                <div class="card-body px-0">
                                    <p><strong>Debit</strong> - use first, pay later</p>
                                    @if (Session["accountInfo"] == null)
                                    {
                                        <a href="@Url.Action("Login","Account", new { Area = "" })" class="btn btn-primary my-2 form-control">Login</a>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("CheckoutDebit","Recharge", new { Area = "Recharge" })" class="btn btn-primary my-2 form-control">Confirm</a>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="wizard-footer d-flex justify-content-between">
                    <a class="btn btn-secondary my-2" href="@Url.Action("RechargeDetail", "Recharge", new { Area = "Recharge" })">
                        <i class="fe-icon-arrow-left"></i>
                        <span class="d-none d-sm-inline-block">Back</span>
                    </a>
                    <a class="btn btn-primary my-2" href="@Url.Action("CheckoutReview", "Recharge", new { Area = "Recharge" })">
                        <span class="d-none d-sm-inline-block">Continue</span>
                        <i class="fe-icon-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>
        <!-- Sidebar-->
        <aside class="col-xl-3 col-lg-4 pb-4 mb-2">
            <!-- Order Summary-->
            <div class="widget">
                <h4 class="widget-title">Order Summary</h4>
                <div class="d-flex justify-content-between pb-2">
                    <div>Packer Name:</div>
                    <div class="font-weight-medium">@ViewBag.PackerName</div>
                </div>
                <div class="d-flex justify-content-between pb-2">
                    <div>Cart subtotal:</div>
                    <div class="font-weight-medium">$@ViewBag.Price</div>
                </div>
                <div class="d-flex justify-content-between pb-2">
                    <div>Tax:</div>
                    <div class="font-weight-medium">$0</div>
                </div>
                <hr>
                <div class="pt-3 text-right text-lg font-weight-medium">$@ViewBag.Price</div>
            </div>
        </aside>
    </div>
</div>

Recharge_Mobile/Areas/Recharge/Views/Recharge/CheckoutReview.cshtml
@{
    ViewBag.Title = "CheckoutReview";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Title-->
<div class="page-title d-flex" aria-label="Page title" style="background-image: url(img/page-title/shop-pattern.jpg);">
    <div class="container text-left align-self-center">
        <h1 class="page-title-heading">Checkout</h1>
    </div>
</div>
<!-- Page Content-->
<div class="container pb-4 mb-2">
    <div class="row">
        <!-- Checkout: Review-->
        <div class="col-xl-9 col-lg-8 pb-5">
            <div class="wizard">
                <div class="wizard-body">
                    <h3 class="h5 pb-3">Review Your Order</h3>
                    <!-- Item-->
                    <div class="cart-item d-md-flex justify-content-between pr-2">
                        <div class="px-3 my-3">
                            <div class="cart-item-product" href="shop-single.html">
                                <div class="cart-item-product-info">
                                    <h4 class="cart-item-product-title">@ViewBag.packageName</h4>
                                    <span><strong>Call:</strong> @(ViewBag.packageTime / 60) minutes</span>
                                    <span><strong>Valid:</strong> @ViewBag.packageDuration days</span>
                                </div>
                            </div>
                        </div>
                        <div class="px-3 my-3 text-center">
                            <div class="cart-item-label">Quantity</div><span class="text-xl font-weight-medium">1</span>
                        </div>
                        <div class="px-3 my-3 text-center">
                            <div class="cart-item-label">Subtotal</div><span class="text-xl font-weight-medium">$@ViewBag.packagePrice</span>
                        </div>
                    </div>
                    <div class="text-right pb-4"><span class="text-muted">Subtotal:</span><span class="text-xl font-weight-medium">&nbsp;$@ViewBag.packagePrice</span></div>
                    <div class="row">
                        <div class="col-sm-6">
                            <h4 class="h6">Payment method:</h4>
                            <ul class="list-unstyled">
                                <li><span class="text-muted">@TempData["paymentMethod"]&nbsp;</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="wizard-footer d-flex justify-content-between">
                    <a class="btn btn-secondary my-2" href="@Url.Action("CheckoutPayment","Recharge", new { Area = "Recharge" })">
                        <i class="fe-icon-arrow-left"></i>
                        <span class="d-none d-sm-inline-block">Back</span>
                    </a>
                    <a class="btn btn-info my-2" href="@Url.Action("GenerateInvoicePDF","Recharge", new { Area = "Recharge" })" runat="server">
                        <i class="fe-icon-download"></i>
                        <span class="d-none d-sm-inline-block">Invoice</span>
                    </a>
                    <a class="btn btn-primary my-2" href="@Url.Action("CheckoutComplete","Recharge", new { Area = "Recharge" })">Complete Order</a>
                </div>
            </div>
        </div>
    </div>
</div>

Recharge_Mobile/Areas/Recharge/Views/Recharge/CheckoutTransaction.cshtml
@model Recharge_Mobile.Areas.User.Models.Views.TransactionModelView
@{
    ViewBag.Title = "CheckoutTransaction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Title-->
<div class="page-title d-flex" aria-label="Page title" style="background-image: url(img/page-title/shop-pattern.jpg);">
    <div class="container text-left align-self-center">
        <h1 class="page-title-heading">Checkout</h1>
    </div>
</div>
<!-- Page Content-->
<div class="container pb-4 mb-2">
    <div class="row">
        <!-- Checkout: Payment-->
        <div class="col-xl-9 col-lg-8 pb-5">
            <div class="wizard">
                @*<div class="wizard-steps d-flex flex-wrap flex-sm-nowrap justify-content-between">
                        <a class="wizard-step" href="checkout-address.html"><i class="fe-icon-check-circle"></i>1. Address</a><a class="wizard-step" href="checkout-shipping.html"><i class="fe-icon-check-circle"></i>2. Shipping</a>
                        <div class="wizard-step active">3. Payment</div><a class="wizard-step" href="checkout-review.html">4. Review</a>
                    </div>*@
                <div class="wizard-body">
                    <h3 class="h5 pb-3">Choose Payment Method</h3>
                    <div class="accordion accordion-style-2" id="accordion" role="tablist">
                        <div class="card">
                            <div class="card-header" role="tab">
                                <h6><a class="pl-0" href="#card" data-toggle="collapse"><i class="fe-icon-credit-card"></i>Pay with Credit Card</a></h6>
                            </div>
                            <div class="collapse show" id="card" data-parent="#accordion" role="tabpanel">
                                <div class="card-body px-0">
                                    <p>We accept following credit cards:&nbsp;&nbsp;<img class="d-inline-block align-middle" src="~/Content/img/credit-cards.png" style="width: 120px;" alt="Cerdit Cards"></p>
                                    <div class="card-wrapper"></div>
                                    @using (Html.BeginForm("CheckoutTransaction", "Recharge", FormMethod.Post, new { @class = "interactive-credit-card row" }))
                                    {
                                        <div class="form-group col-sm-6">
                                            <input class="form-control" type="text" name="number" placeholder="Card Number" required>
                                        </div>
                                        <div class="form-group col-sm-6">
                                            <input class="form-control" type="text" name="name" placeholder="Full Name" required>
                                        </div>
                                        <div class="form-group col-sm-3">
                                            <input class="form-control" type="text" name="expire" placeholder="MM/YY" required>
                                        </div>
                                        <div class="form-group col-sm-3">
                                            <input class="form-control" type="text" name="cvc" placeholder="CVC" required>
                                        </div>
                                        <div class="col-sm-6">
                                            <button class="btn btn-primary btn-block mt-0" type="submit">Submit</button>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab">
                                <h6><a class="collapsed pl-0" href="#paypal" data-toggle="collapse"><i class="socicon-paypal"></i>Pay with PayPal</a></h6>
                            </div>
                            <div class="collapse" id="paypal" data-parent="#accordion" role="tabpanel">
                                <div class="card-body px-0">
                                    <p><strong>PayPal</strong> - the safer, easier way to pay</p>
                                    <a href="@Url.Action("PaymentWithPaypal", "PayPal", new { Area = "Recharge" })" class="btn btn-primary my-2 form-control">Login</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="wizard-footer d-flex justify-content-between">
                    <a class="btn btn-secondary my-2" href="@Url.Action("AccountDebit", "User", new { Area = "User" })">
                        <i class="fe-icon-arrow-left"></i>
                        <span class="d-none d-sm-inline-block">Back</span>
                    </a>
                    <a class="btn btn-primary my-2" href="@Url.Action("TransactionReview", "Recharge", new { Area = "Recharge" })">
                        <span class="d-none d-sm-inline-block">Continue</span>
                        <i class="fe-icon-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>
        <!-- Sidebar-->
        <aside class="col-xl-3 col-lg-4 pb-4 mb-2">
            <!-- Order Summary-->
            <div class="widget">
                <h4 class="widget-title">Order Summary</h4>
                <div class="d-flex justify-content-between pb-2">
                    <div>Packer Name:</div>
                    <div class="font-weight-medium">@Model.RechargeName</div>
                </div>
                <div class="d-flex justify-content-between pb-2">
                    <div>Cart subtotal:</div>
                    <div class="font-weight-medium">$@Model.Price</div>
                </div>
                <div class="d-flex justify-content-between pb-2">
                    <div>Tax:</div>
                    <div class="font-weight-medium">$0</div>
                </div>
                <hr>
                <div class="pt-3 text-right text-lg font-weight-medium">$@Model.Price</div>
            </div>
        </aside>
    </div>
</div>