Recharge_Mobile/Areas/AdminArea/Controllers/TransactionAdminController.cs
using CDStore.Models.Filters;
using Recharge_Mobile.Areas.AdminArea.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Recharge_Mobile.Areas.AdminArea.Controllers
{
    [CAuthFilter(RoleName = "Admin")]
    public class TransactionAdminController : Controller
    {
        TransactionAdminDAO transactionAdminDAO;
        // GET: AdminArea/TransactionAdmin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TransactionList()
        {
            transactionAdminDAO = new TransactionAdminDAO();
            var resultList = transactionAdminDAO.TransactionList();
            return View(resultList);
        }

        public ActionResult TransactionListByDate()
        {
            transactionAdminDAO = new TransactionAdminDAO();
            var result = transactionAdminDAO.TransactionListByDate(DateTime.Now);
            var resultList = result.Item1;
            ViewBag.totalAmount = result.Item2;
            return View(resultList);
        }
        [HttpPost]
        public ActionResult TransactionListByDate(DateTime checkdate)
        {
            transactionAdminDAO = new TransactionAdminDAO();
            var result = transactionAdminDAO.TransactionListByDate(checkdate);
            var resultList = result.Item1;
            ViewBag.totalAmount = result.Item2;
            ViewBag.daycheck = checkdate;
            return View(resultList);
        }

        public ActionResult AdvanceSearch()
        {
            AdvanceSearchVM vm = new AdvanceSearchVM();
            vm.DateFrom = DateTime.Now.Date;
            vm.DateTo = DateTime.Now.Date;
            vm.RechargeType = "None";
            vm.PaymentMethod = "None";
            vm.Status = "None";
            return View(vm);
        }
        [HttpPost]
        public ActionResult AdvanceSearch(AdvanceSearchVM vm)
        {
            if (ModelState.IsValid)
            {
                if(vm.DateFrom > vm.DateTo)
                {
                    ModelState.AddModelError("InvalidDay", "Date-to must greater or equal Date-from!");
                    return View(vm);
                }
                transactionAdminDAO = new TransactionAdminDAO();
                ViewBag.SearchResultList = transactionAdminDAO.AdvanceSearch(vm).Item1;
                ViewBag.TotalAmount = transactionAdminDAO.AdvanceSearch(vm).Item2;
                return View(vm);
            }
            return View(vm);
        }
    }
}

Recharge_Mobile/Areas/AdminArea/Views/TransactionAdmin/AdvanceSearch.cshtml
@model Recharge_Mobile.Areas.AdminArea.Models.AdvanceSearchVM
@using Recharge_Mobile.Areas.AdminArea.Models

@{
    ViewBag.Title = "AdvanceSearch";
    Layout = "~/Areas/AdminArea/Views/Shared/_LayoutAdmin.cshtml";
}

<h3 style="color: purple; text-align: center">Advanced Search</h3>


@using (Html.BeginForm("AdvanceSearch", "TransactionAdmin", new { area = "AdminArea" }))
{
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

<div class="form-horizontal">
    <hr /><br />
        <div class="row">
            <div class="form-group col-lg-6">
                <label for="DateFrom" class="mr-sm-2">Date From</label>
                <input class="custom-select form-control mb-2 mr-sm-2" type="date" name="DateFrom" id="DateFrom" value="@Model.DateFrom.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group col-lg-6">
                <label for="DateTo" class="mr-sm-2">Date To</label>
                <input class="custom-select form-control mb-2 mr-sm-2" type="date" name="DateTo" id="DateTo" value="@Model.DateTo.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group col-lg-6">
                <label for="PhoneNumber" class="mr-sm-2">Phone Number</label>
                <input class="custom-select form-control mb-2 mr-sm-2" type="text" pattern="[0-9]{3,10}" title="3-10 numbers" name="PhoneNumber" id="PhoneNumber" value="@Model.PhoneNumber" />
            </div>
            <div class="form-group col-lg-6">
                <label for="RechargeType" class="mr-sm-2">Recharge Type</label>
                <select class="custom-select form-control mb-2 mr-sm-2" name="RechargeType" id="RechargeType">
                    @if (Model.RechargeType == "None")
                    {
                        <option value="None" selected>--All--</option>
                        <option value="Regular">Regular</option>
                        <option value="Special">Special</option>
                    }
                    else if (Model.RechargeType == "Regular")
                    {
                        <option value="None">--All--</option>
                        <option value="Regular" selected>Regular</option>
                        <option value="Special">Special</option>
                    }
                    else if (Model.RechargeType == "Special")
                    {
                        <option value="None">--All--</option>
                        <option value="Regular">Regular</option>
                        <option value="Special" selected>Special</option>
                    }
                </select>
            </div>
            <div class="form-group col-lg-6">
                <label for="PaymentMethod" class="mr-sm-2">Payment Method</label>
                <select class="custom-select form-control mb-2 mr-sm-2" name="PaymentMethod" id="PaymentMethod">
                    @if (Model.PaymentMethod == "None")
                    {
                        <option value="None" selected>--All--</option>
                        <option value="Credit Card">Credit Card</option>
                        <option value="Paypal">Paypal</option>
                        <option value="Debit">Debit</option>
                    }
                    else if (Model.PaymentMethod == "Credit Card")
                    {
                        <option value="None">--All--</option>
                        <option value="Credit Card" selected>Credit Card</option>
                        <option value="Paypal">Paypal</option>
                        <option value="Debit">Debit</option>
                    }
                    else if (Model.PaymentMethod == "Paypal")
                    {
                        <option value="None">--All--</option>
                        <option value="Credit Card">Credit Card</option>
                        <option value="Paypal" selected>Paypal</option>
                        <option value="Debit">Debit</option>
                    }
                    else if (Model.PaymentMethod == "Debit")
                    {
                        <option value="None">--All--</option>
                        <option value="Credit Card">Credit Card</option>
                        <option value="Paypal">Paypal</option>
                        <option value="Debit" selected>Debit</option>
                    }
                </select>
            </div>
            <div class="form-group col-lg-6">
                <label for="Status" class="mr-sm-2">Status</label>
                <select class="custom-select form-control mb-2 mr-sm-2" name="Status" id="Status">
                    @if (Model.Status == "None")
                    {
                        <option value="None" selected>--All--</option>
                        <option value="Paid">Paid</option>
                        <option value="Unpaid">Unpaid</option>
                    }
                    else if (Model.Status == "Paid")
                    {
                        <option value="None">--All--</option>
                        <option value="Paid" selected>Paid</option>
                        <option value="Unpaid">Unpaid</option>
                    }
                    else if (Model.Status == "Unpaid")
                    {
                        <option value="None">--All--</option>
                        <option value="Paid">Paid</option>
                        <option value="Unpaid" selected>Unpaid</option>
                    }
                </select>
            </div>
        </div>
        
        <button class="btn btn-gradient" type="submit">Search</button>
</div>
}
@if (ViewBag.SearchResultList != null)
{
    if (((IList<TransactionAdminVM>)(ViewBag.SearchResultList)).Count() >= 1)
    {
        <br />
        <p><strong>Total Amount Purchase: $@ViewBag.TotalAmount</strong></p>
        <div style="height: 400px;overflow: scroll;">
            <table class="table table-hover">
                <tr>
                    <th>
                        Phone Number
                    </th>
                    <th>
                        Type Recharge
                    </th>
                    <th>
                        Type Packet
                    </th>
                    <th>
                        Recharge Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Date
                    </th>
                    <th>
                        Post Payment
                    </th>
                    <th>
                        Status
                    </th>
                </tr>

                @foreach (TransactionAdminVM item in (IList<TransactionAdminVM>)(ViewBag.SearchResultList))
                {
                    <tr>
                        <td>
                            @item.PhoneNumber
                        </td>
                        <td>
                            @item.PaymentMethod
                        </td>
                        <td>
                            @item.RechargeType
                        </td>
                        <td>
                            @item.RechargeName
                        </td>
                        <td>
                            @item.Amount
                        </td>
                        <td>
                            @item.DateTime
                        </td>
                        <td>
                            @item.PostPayment
                        </td>
                        <td>
                            @item.Status
                        </td>
                    </tr>
                }
            </table>
        </div>
            }
            else
            {
            <h3 class="alert-warning">No result found!</h3>
            }
            }


            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

Recharge_Mobile/Areas/AdminArea/Views/TransactionAdmin/TransactionList.cshtml
@model IEnumerable<Recharge_Mobile.Areas.AdminArea.Models.TransactionAdminVM>

@{
    ViewBag.Title = "TransactionList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color: purple; text-align: center">TransactionList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TransactionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RechargeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RRechargeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SRechargeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentMethod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RechargeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostPayment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.TransactionId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PhoneNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RechargeType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RRechargeId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SRechargeId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PaymentMethod)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RechargeName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Amount)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateTime)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PostPayment)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Status)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
    </td>
</tr>
}

</table>

Recharge_Mobile/Areas/AdminArea/Views/TransactionAdmin/TransactionListByDate.cshtml
@model IEnumerable<Recharge_Mobile.Areas.AdminArea.Models.TransactionAdminVM>

@{
    ViewBag.Title = "TransactionListByDate";
    Layout = "~/Areas/AdminArea/Views/Shared/_LayoutAdmin.cshtml";
}

<h3 style="color: purple; text-align: center">Daily Report</h3>
<div class="container">
    <div class="row mb-3">
        <div class="col"></div>
        <div class="col">
            <div class="float-right">
                @using (Html.BeginForm("TransactionListByDate", "TransactionAdmin", new { area = "AdminArea" }))
                {
                    if (ViewBag.daycheck != null)
                    {
                        <input class="custom-select" type="date" id="checkdate" name="checkdate" value="@ViewBag.daycheck.ToString("yyyy-MM-dd")" onchange="this.form.submit()">
                    }
                    else
                    {
                        <input class="custom-select" type="date" id="checkdate" name="checkdate" value="@DateTime.Now.ToString("yyyy-MM-dd")" onchange="this.form.submit()">
                    }
                }
            </div>
        </div>
    </div>
</div>

@*<span id="btnchange" class="btn btn-default">change</span>*@

<p class="font-weight-bold">
    Total Amount: $@ViewBag.totalAmount
</p>
<table class="table table-hover">
    <tr>
        <th>
            Phonenumer
        </th>
        <th>
            Payment Method
        </th>
        <th>
            Recharge Type
        </th>
        <th>
            Recharge Name
        </th>
        <th>
            Price
        </th>
        <th>
            Date
        </th>
        <th>
            Post Payment
        </th>
        <th>
            Status
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentMethod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RechargeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RechargeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostPayment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
            </td>
        </tr>
    }

</table>

@section scripts {
    @*<script type="text/javascript">

            $(document).ready(function () {
                $("#btnchange").click(function () {
                    $.ajax({
                        url: 'TransactionListByDate',
                        method: "post",
                        data: {
                            CheckDate: $("#checkdate").val()
                        },
                        success: function (response) {
                            window.location.reload();
                        }
                    });
                });
            });

        </script>*@
}